<a href="https://colab.research.google.com/github/shree026/ML_data/blob/master/Ml_data_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
import pandas as pd

In [0]:
data=pd.read_csv('Data.csv')

In [3]:
print(data.shape)

(10, 4)


In [4]:
data.head(20)

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [5]:
data.info()


<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
Country      10 non-null object
Age          9 non-null float64
Salary       9 non-null float64
Purchased    10 non-null object
dtypes: float64(2), object(2)
memory usage: 448.0+ bytes


In [6]:
types = data.dtypes
print(types)


Country       object
Age          float64
Salary       float64
Purchased     object
dtype: object


In [0]:
x= data.iloc[:,:-1].values  

In [8]:
print(x)


[['France' 44.0 72000.0]
 ['Spain' 27.0 48000.0]
 ['Germany' 30.0 54000.0]
 ['Spain' 38.0 61000.0]
 ['Germany' 40.0 nan]
 ['France' 35.0 58000.0]
 ['Spain' nan 52000.0]
 ['France' 48.0 79000.0]
 ['Germany' 50.0 83000.0]
 ['France' 37.0 67000.0]]


In [9]:
y=data.iloc[:,3].values  
print(y)


['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


In [0]:
y= data.iloc[:,3].values 


In [0]:

import matplotlib.pyplot as plt

In [0]:
from matplotlib import pyplot

In [0]:
from sklearn.preprocessing import Imputer  

In [21]:
imputer= Imputer(missing_values ='NaN', strategy='mean', axis = 0)  


/usr/local/lib/python3.6/dist-packages/sklearn/utils/deprecation.py:66: DeprecationWarning: Class Imputer is deprecated; Imputer was deprecated in version 0.20 and will be removed in 0.22. Import impute.SimpleImputer from sklearn instead.
  warnings.warn(msg, category=DeprecationWarning)


In [0]:
imputerimputer= imputer.fit(x[:, 1:3])  


In [0]:
x[:, 1:3]= imputer.transform(x[:, 1:3])  


In [0]:
from sklearn.preprocessing import LabelEncoder

In [0]:
label_encoder_x= LabelEncoder() 

In [0]:
x[:, 0]= label_encoder_x.fit_transform(x[:, 0])  


In [0]:
from sklearn.preprocessing import OneHotEncoder

In [0]:
one_hot_encoder= OneHotEncoder(categorical_features= [0])    


In [26]:
x= one_hot_encoder.fit_transform(x).toarray()  


/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:415: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:451: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [27]:
print(x)

[[1.00000000e+00 0.00000000e+00 0.00000000e+00 4.40000000e+01
  7.20000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 2.70000000e+01
  4.80000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 3.00000000e+01
  5.40000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.80000000e+01
  6.10000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 4.00000000e+01
  6.37777778e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.50000000e+01
  5.80000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 3.87777778e+01
  5.20000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 4.80000000e+01
  7.90000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 5.00000000e+01
  8.30000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.70000000e+01
  6.70000000e+04]]


In [0]:
x[:, 3]= label_encoder_x.fit_transform(x[:, 3])  

In [29]:
print(x)

[[1.00000000e+00 0.00000000e+00 0.00000000e+00 7.00000000e+00
  7.20000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 0.00000000e+00
  4.80000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 1.00000000e+00
  5.40000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 4.00000000e+00
  6.10000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 6.00000000e+00
  6.37777778e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 2.00000000e+00
  5.80000000e+04]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00 5.00000000e+00
  5.20000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 8.00000000e+00
  7.90000000e+04]
 [0.00000000e+00 1.00000000e+00 0.00000000e+00 9.00000000e+00
  8.30000000e+04]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00 3.00000000e+00
  6.70000000e+04]]


In [0]:
from sklearn.model_selection import train_test_split

In [0]:
x_train,x_test,y_train,t_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [0]:
from sklearn.preprocessing import StandardScaler 

In [0]:
standard_scaler = StandardScaler()

In [0]:
x_train=standard_scaler.fit_transform(x_train)

In [39]:
print(x_train)

[[-1.          2.64575131 -0.77459667  0.65081403  0.12381479]
 [ 1.         -0.37796447 -0.77459667 -0.55068879  0.46175632]
 [-1.         -0.37796447  1.29099445 -1.75219161 -1.53093341]
 [-1.         -0.37796447  1.29099445  0.25031309 -1.11141978]
 [ 1.         -0.37796447 -0.77459667  1.45181591  1.7202972 ]
 [-1.         -0.37796447  1.29099445 -0.15018785 -0.16751412]
 [ 1.         -0.37796447 -0.77459667  1.05131497  0.98614835]
 [ 1.         -0.37796447 -0.77459667 -0.95118973 -0.48214934]]
